name = "PDBenchmark"
uuid = "6e2c50fb-dcbe-4ee9-af49-f66558480dd2"
authors = ["Ravinder Bhattoo <ravinderbhattoo@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PDMaterialPoints = "699b3a5d-6dba-4e2a-88ec-3ad113d1b49e"
PeriDyn = "c3db0ce0-6d7e-41b5-be11-bcb6aafada44"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
