name = "PDBenchmark"
uuid = "6e2c50fb-dcbe-4ee9-af49-f66558480dd2"
authors = ["Ravinder Bhattoo <ravinderbhattoo@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PDMesh = "699b3a5d-6dba-4e2a-88ec-3ad113d1b49e"
PeriDyn = "c3db0ce0-6d7e-41b5-be11-bcb6aafada44"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
